# Generated by Django 6.0.2 on 2026-02-28 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('bankroll_challenge', 'Bankroll Challenge'), ('timed_rounds', 'Timed Rounds')], max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=10)),
                ('starting_balance', models.IntegerField(default=1000)),
                ('hand_limit', models.IntegerField(blank=True, help_text='Max hands for bankroll challenge', null=True)),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Minutes for timed rounds', null=True)),
                ('num_decks', models.IntegerField(default=6)),
                ('max_players', models.IntegerField(default=20)),
                ('start_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('final_balance', models.IntegerField(blank=True, null=True)),
                ('hands_played', models.IntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', '-final_balance'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
