# Generated by Django 6.0.2 on 2026-02-28 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('starting_balance', models.IntegerField(default=1000)),
                ('final_balance', models.IntegerField(blank=True, null=True)),
                ('hands_played', models.IntegerField(default=0)),
                ('num_decks', models.IntegerField(default=6)),
                ('is_complete', models.BooleanField(default=False)),
                ('tournament_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to='tournaments.tournamententry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HandResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_number', models.PositiveIntegerField()),
                ('player_cards', models.JSONField()),
                ('dealer_cards', models.JSONField()),
                ('bet', models.IntegerField()),
                ('payout', models.IntegerField()),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('push', 'Push'), ('blackjack', 'Blackjack')], max_length=10)),
                ('running_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='game.gamesession')),
            ],
            options={
                'ordering': ['hand_number'],
                'unique_together': {('session', 'hand_number')},
            },
        ),
    ]
